package proto.message;

@javax.annotation.Generated("/Users/vunguyen/project/gdxsocket/core/src/proto/msg_profile.proto")
public enum ProfileCommand implements io.protostuff.EnumLite<ProfileCommand>{

    PROFILE_GET_USER_MONEY_REQUEST(1),
    PROFILE_GET_USER_MONEY_RESPONSE(2),
    PROFILE_GET_USER_PROFILE_REQUEST(3),
    PROFILE_GET_USER_PROFILE_RESPONSE(4),
    PROFILE_LEVEL_UP_RESPONSE(5),
    PROFILE_GET_USER_INBOX_REQUEST(6),
    PROFILE_GET_USER_INBOX_RESPONSE(7),
    PROFILE_CLAIM_INBOX_REQUEST(8),
    PROFILE_CLAIM_INBOX_RESPONSE(9),
    PROFILE_UPDATE_USER_PROFILE_FB_REQUEST(10),
    PROFILE_UPDATE_USER_PROFILE_FB_RESPONSE(11),
    PROFILE_UPDATE_USER_NAME_REQUEST(12),
    PROFILE_UPDATE_USER_NAME_RESPONSE(13),
    PROFILE_FRIEND_LIST_RAW_REQUEST(14),
    PROFILE_FRIEND_LIST_RAW_RESPONSE(15),
    PROFILE_FRIEND_LIST_DETAIL_REQUEST(16),
    PROFILE_FRIEND_LIST_DETAIL_RESPONSE(17),
    PROFILE_FRIEND_INVITATION_DETAIL_REQUEST(18),
    PROFILE_FRIEND_INVITATION_DETAIL_RESPONSE(19),
    PROFILE_FRIEND_REMOVE_REQUEST(20),
    PROFILE_FRIEND_REMOVE_RESPONSE(21),
    PROFILE_FRIEND_INVITATION_SEND_REQUEST(22),
    PROFILE_FRIEND_INVITATION_SEND_RESPONSE(23),
    PROFILE_FRIEND_INVITATION_ACCEPT_REQUEST(24),
    PROFILE_FRIEND_INVITATION_ACCEPT_RESPONSE(25),
    PROFILE_FRIEND_INVITATION_DENY_REQUEST(26),
    PROFILE_FRIEND_INVITATION_DENY_RESPONSE(27),
    PROFILE_FRIEND_SEARCH_REQUEST(28),
    PROFILE_FRIEND_SEARCH_RESPONSE(29),
    PROFILE_FRIEND_LOCK_MONEY_SEND_REQUEST(30),
    PROFILE_FRIEND_LOCK_MONEY_SEND_RESPONSE(31),
    PROFILE_FRIEND_LOCK_MONEY_RECEIVE_REQUEST(32),
    PROFILE_FRIEND_LOCK_MONEY_RECEIVE_RESPONSE(33),
    PROFILE_FRIEND_UNLOCK_MONEY_SEND_REQUEST(34),
    PROFILE_FRIEND_UNLOCK_MONEY_SEND_RESPONSE(35),
    PROFILE_FRIEND_MESSAGE_SEND_REQUEST(36),
    PROFILE_FRIEND_MESSAGE_SEND_RESPONSE(37),
    PROFILE_DAILY_QUEST_INFO_REQUEST(38),
    PROFILE_DAILY_QUEST_INFO_RESPONSE(39),
    PROFILE_DAILY_QUEST_RECEIVE_REQUEST(40),
    PROFILE_DAILY_QUEST_RECEIVE_RESPONSE(41),
    PROFILE_DAILY_SNS_FRIEND_INVITE_REQUEST(42),
    PROFILE_DAILY_SNS_FRIEND_INVITE_RESPONSE(43),
    PROFILE_GIFTCODE_REQUEST(44),
    PROFILE_GIFTCODE_RESPONSE(45),
    PROFILE_GET_INVENTORY_REQUEST(46),
    PROFILE_GET_INVENTORY_RESPONSE(47),
    PROFILE_GET_CANNON_DATA_REQUEST(48),
    PROFILE_GET_CANNON_DATA_RESPONSE(49),
    PROFILE_CANNON_UNLOCK_REQUEST(50),
    PROFILE_CANNON_UNLOCK_RESPONSE(51),
    PROFILE_CANNON_UPGRADE_REQUEST(52),
    PROFILE_CANNON_UPGRADE_RESPONSE(53),
    PROFILE_DAILY_SUPPORT_REQUEST(54),
    PROFILE_WHEEL_ENTER_REQUEST(55),
    PROFILE_WHEEL_ENTER_RESPONSE(56),
    PROFILE_WHEEL_LEAVE_REQUEST(57),
    PROFILE_WHEEL_LEAVE_RESPONSE(58),
    PROFILE_WHEEL_TURN_REQUEST(59),
    PROFILE_WHEEL_TURN_RESPONSE(60),
    PROFILE_WHEEL_GET_REQUEST(61),
    PROFILE_WHEEL_GET_RESPONSE(62),
    PROFILE_WHEEL_INGAME_REQUEST(63),
    PROFILE_WHEEL_INGAME_RESPONSE(64),
    PROFILE_WHEEL_CARRIER_REQUEST(65),
    PROFILE_WHEEL_CARRIER_RESPONSE(66),
    PROFILE_SOCCER_ENTER_REQUEST(67),
    PROFILE_SOCCER_ENTER_RESPONSE(68),
    PROFILE_SOCCER_TEAMS_RESPONSE(69),
    PROFILE_SOCCER_MATCHES_REQUEST(70),
    PROFILE_SOCCER_MATCHES_RESPONSE(71),
    PROFILE_SOCCER_BET_REQUEST(72),
    PROFILE_SOCCER_BET_RESPONSE(73),
    PROFILE_SOCCER_BET_COUNT_RESPONSE(74),
    PROFILE_SOCCER_RECEIVE_REQUEST(75),
    PROFILE_SOCCER_RECEIVE_RESPONSE(76),
    PROFILE_SOCCER_REDDOT_REQUEST(77),
    PROFILE_SOCCER_REDDOT_RESPONSE(78),
    PROFILE_PET_INFO_REQUEST(79),
    PROFILE_PET_INFO_RESPONSE(80),
    PROFILE_PET_UPDATE_RESPONSE(81),
    PROFILE_PET_UNLOCK_REQUEST(82),
    PROFILE_PET_UNLOCK_RESPONSE(83),
    PROFILE_PET_GIFT_RECEIVE_REQUEST(84),
    PROFILE_PET_GIFT_RECEIVE_RESPONSE(85),
    PROFILE_PET_GIFT_ASKING_REQUEST(86),
    PROFILE_PET_GIFT_ASKING_RESPONSE(87),
    PROFILE_CLIENT_ACTION_LOG_REQUEST(89),
    PROFILE_ADS_VIEW_REQUEST(90),
    PROFILE_ADS_VIEW_RESPONSE(91),
    PROFILE_PET_LEVELUP_RESPONSE(92),
    PROFILE_DAILY_SUPPORT_RESPONSE(93),
    PROFILE_DAILY_BONUS_REQUEST(94),
    PROFILE_DAILY_BONUS_RESPONSE(95),
    PROFILE_CLAIM_DAILY_BONUS_REQUEST(96),
    PROFILE_CLAIM_DAILY_BONUS_RESPONSE(97),
    PROFILE_COLLECTION_DATA_REQUEST(98),
    PROFILE_COLLECTION_DATA_RESPONSE(99),
    PROFILE_COLLECTION_CLAIM_PRIZE_REQUEST(100),
    PROFILE_COLLECTION_CLAIM_PRIZE_RESPONSE(101),
    PROFILE_DONATE_FRIEND_LIST_DETAIL_REQUEST(102),
    PROFILE_DONATE_FRIEND_LIST_DETAIL_RESPONSE(103),
    PROFILE_DONATE_RECEIVE_ITEMS_REQUEST(104),
    PROFILE_DONATE_RECEIVE_ITEMS_RESPONSE(105),
    PROFILE_DONATE_SEND_ITEMS_REQUEST(106),
    PROFILE_DONATE_SEND_ITEMS_RESPONSE(107),
    PROFILE_DONATE_CHECK_GIFT_REQUEST(108),
    PROFILE_DONATE_CHECK_GIFT_RESPONSE(109),
    PROFILE_DONATE_LIST_FRIEND_SEND_ITEMS_REQUEST(110),
    PROFILE_DONATE_LIST_FRIEND_SEND_ITEMS_RESPONSE(111),
    PROFILE_ACCUMULATE_PROMOTION_REQUEST(112),
    PROFILE_ACCUMULATE_PROMOTION_RESPONSE(113),
    PROFILE_ACCUMULATE_CLAIM_REQUEST(114),
    PROFILE_ACCUMULATE_CLAIM_RESPONSE(115),
    PROFILE_LEADERBOARD_REQUEST(116),
    PROFILE_LEADERBOARD_RESPONSE(117),
    PROFILE_ARCHIVE_COLLECTION_REQUEST(118),
    PROFILE_ARCHIVE_COLLECTION_RESPONSE(119),
    PROFILE_ADS_INFO_REQUEST(120),
    PROFILE_ADS_INFO_RESPONSE(121),
    PROFILE_ADS_REWARD_CLAIM_REQUEST(122),
    PROFILE_H3_ENTER_REQUEST(123),
    PROFILE_H3_ENTER_RESPONSE(124),
    PROFILE_H3_LEAVE_REQUEST(125),
    PROFILE_H3_LEAVE_RESPONSE(126),
    PROFILE_H3_TURN_REQUEST(127),
    PROFILE_H3_TURN_RESPONSE(128),
    UNRECOGNIZED(-1);

    private final int value;

    private ProfileCommand(int n) {
        this.value = n;
    }

    @Override
    public int getNumber() {
        if (value == -1) {
          throw new java.lang.IllegalStateException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
    }

    public static final ProfileCommand valueOf(int tag) {
        switch(tag) {
            case 1: return PROFILE_GET_USER_MONEY_REQUEST;
            case 2: return PROFILE_GET_USER_MONEY_RESPONSE;
            case 3: return PROFILE_GET_USER_PROFILE_REQUEST;
            case 4: return PROFILE_GET_USER_PROFILE_RESPONSE;
            case 5: return PROFILE_LEVEL_UP_RESPONSE;
            case 6: return PROFILE_GET_USER_INBOX_REQUEST;
            case 7: return PROFILE_GET_USER_INBOX_RESPONSE;
            case 8: return PROFILE_CLAIM_INBOX_REQUEST;
            case 9: return PROFILE_CLAIM_INBOX_RESPONSE;
            case 10: return PROFILE_UPDATE_USER_PROFILE_FB_REQUEST;
            case 11: return PROFILE_UPDATE_USER_PROFILE_FB_RESPONSE;
            case 12: return PROFILE_UPDATE_USER_NAME_REQUEST;
            case 13: return PROFILE_UPDATE_USER_NAME_RESPONSE;
            case 14: return PROFILE_FRIEND_LIST_RAW_REQUEST;
            case 15: return PROFILE_FRIEND_LIST_RAW_RESPONSE;
            case 16: return PROFILE_FRIEND_LIST_DETAIL_REQUEST;
            case 17: return PROFILE_FRIEND_LIST_DETAIL_RESPONSE;
            case 18: return PROFILE_FRIEND_INVITATION_DETAIL_REQUEST;
            case 19: return PROFILE_FRIEND_INVITATION_DETAIL_RESPONSE;
            case 20: return PROFILE_FRIEND_REMOVE_REQUEST;
            case 21: return PROFILE_FRIEND_REMOVE_RESPONSE;
            case 22: return PROFILE_FRIEND_INVITATION_SEND_REQUEST;
            case 23: return PROFILE_FRIEND_INVITATION_SEND_RESPONSE;
            case 24: return PROFILE_FRIEND_INVITATION_ACCEPT_REQUEST;
            case 25: return PROFILE_FRIEND_INVITATION_ACCEPT_RESPONSE;
            case 26: return PROFILE_FRIEND_INVITATION_DENY_REQUEST;
            case 27: return PROFILE_FRIEND_INVITATION_DENY_RESPONSE;
            case 28: return PROFILE_FRIEND_SEARCH_REQUEST;
            case 29: return PROFILE_FRIEND_SEARCH_RESPONSE;
            case 30: return PROFILE_FRIEND_LOCK_MONEY_SEND_REQUEST;
            case 31: return PROFILE_FRIEND_LOCK_MONEY_SEND_RESPONSE;
            case 32: return PROFILE_FRIEND_LOCK_MONEY_RECEIVE_REQUEST;
            case 33: return PROFILE_FRIEND_LOCK_MONEY_RECEIVE_RESPONSE;
            case 34: return PROFILE_FRIEND_UNLOCK_MONEY_SEND_REQUEST;
            case 35: return PROFILE_FRIEND_UNLOCK_MONEY_SEND_RESPONSE;
            case 36: return PROFILE_FRIEND_MESSAGE_SEND_REQUEST;
            case 37: return PROFILE_FRIEND_MESSAGE_SEND_RESPONSE;
            case 38: return PROFILE_DAILY_QUEST_INFO_REQUEST;
            case 39: return PROFILE_DAILY_QUEST_INFO_RESPONSE;
            case 40: return PROFILE_DAILY_QUEST_RECEIVE_REQUEST;
            case 41: return PROFILE_DAILY_QUEST_RECEIVE_RESPONSE;
            case 42: return PROFILE_DAILY_SNS_FRIEND_INVITE_REQUEST;
            case 43: return PROFILE_DAILY_SNS_FRIEND_INVITE_RESPONSE;
            case 44: return PROFILE_GIFTCODE_REQUEST;
            case 45: return PROFILE_GIFTCODE_RESPONSE;
            case 46: return PROFILE_GET_INVENTORY_REQUEST;
            case 47: return PROFILE_GET_INVENTORY_RESPONSE;
            case 48: return PROFILE_GET_CANNON_DATA_REQUEST;
            case 49: return PROFILE_GET_CANNON_DATA_RESPONSE;
            case 50: return PROFILE_CANNON_UNLOCK_REQUEST;
            case 51: return PROFILE_CANNON_UNLOCK_RESPONSE;
            case 52: return PROFILE_CANNON_UPGRADE_REQUEST;
            case 53: return PROFILE_CANNON_UPGRADE_RESPONSE;
            case 54: return PROFILE_DAILY_SUPPORT_REQUEST;
            case 55: return PROFILE_WHEEL_ENTER_REQUEST;
            case 56: return PROFILE_WHEEL_ENTER_RESPONSE;
            case 57: return PROFILE_WHEEL_LEAVE_REQUEST;
            case 58: return PROFILE_WHEEL_LEAVE_RESPONSE;
            case 59: return PROFILE_WHEEL_TURN_REQUEST;
            case 60: return PROFILE_WHEEL_TURN_RESPONSE;
            case 61: return PROFILE_WHEEL_GET_REQUEST;
            case 62: return PROFILE_WHEEL_GET_RESPONSE;
            case 63: return PROFILE_WHEEL_INGAME_REQUEST;
            case 64: return PROFILE_WHEEL_INGAME_RESPONSE;
            case 65: return PROFILE_WHEEL_CARRIER_REQUEST;
            case 66: return PROFILE_WHEEL_CARRIER_RESPONSE;
            case 67: return PROFILE_SOCCER_ENTER_REQUEST;
            case 68: return PROFILE_SOCCER_ENTER_RESPONSE;
            case 69: return PROFILE_SOCCER_TEAMS_RESPONSE;
            case 70: return PROFILE_SOCCER_MATCHES_REQUEST;
            case 71: return PROFILE_SOCCER_MATCHES_RESPONSE;
            case 72: return PROFILE_SOCCER_BET_REQUEST;
            case 73: return PROFILE_SOCCER_BET_RESPONSE;
            case 74: return PROFILE_SOCCER_BET_COUNT_RESPONSE;
            case 75: return PROFILE_SOCCER_RECEIVE_REQUEST;
            case 76: return PROFILE_SOCCER_RECEIVE_RESPONSE;
            case 77: return PROFILE_SOCCER_REDDOT_REQUEST;
            case 78: return PROFILE_SOCCER_REDDOT_RESPONSE;
            case 79: return PROFILE_PET_INFO_REQUEST;
            case 80: return PROFILE_PET_INFO_RESPONSE;
            case 81: return PROFILE_PET_UPDATE_RESPONSE;
            case 82: return PROFILE_PET_UNLOCK_REQUEST;
            case 83: return PROFILE_PET_UNLOCK_RESPONSE;
            case 84: return PROFILE_PET_GIFT_RECEIVE_REQUEST;
            case 85: return PROFILE_PET_GIFT_RECEIVE_RESPONSE;
            case 86: return PROFILE_PET_GIFT_ASKING_REQUEST;
            case 87: return PROFILE_PET_GIFT_ASKING_RESPONSE;
            case 89: return PROFILE_CLIENT_ACTION_LOG_REQUEST;
            case 90: return PROFILE_ADS_VIEW_REQUEST;
            case 91: return PROFILE_ADS_VIEW_RESPONSE;
            case 92: return PROFILE_PET_LEVELUP_RESPONSE;
            case 93: return PROFILE_DAILY_SUPPORT_RESPONSE;
            case 94: return PROFILE_DAILY_BONUS_REQUEST;
            case 95: return PROFILE_DAILY_BONUS_RESPONSE;
            case 96: return PROFILE_CLAIM_DAILY_BONUS_REQUEST;
            case 97: return PROFILE_CLAIM_DAILY_BONUS_RESPONSE;
            case 98: return PROFILE_COLLECTION_DATA_REQUEST;
            case 99: return PROFILE_COLLECTION_DATA_RESPONSE;
            case 100: return PROFILE_COLLECTION_CLAIM_PRIZE_REQUEST;
            case 101: return PROFILE_COLLECTION_CLAIM_PRIZE_RESPONSE;
            case 102: return PROFILE_DONATE_FRIEND_LIST_DETAIL_REQUEST;
            case 103: return PROFILE_DONATE_FRIEND_LIST_DETAIL_RESPONSE;
            case 104: return PROFILE_DONATE_RECEIVE_ITEMS_REQUEST;
            case 105: return PROFILE_DONATE_RECEIVE_ITEMS_RESPONSE;
            case 106: return PROFILE_DONATE_SEND_ITEMS_REQUEST;
            case 107: return PROFILE_DONATE_SEND_ITEMS_RESPONSE;
            case 108: return PROFILE_DONATE_CHECK_GIFT_REQUEST;
            case 109: return PROFILE_DONATE_CHECK_GIFT_RESPONSE;
            case 110: return PROFILE_DONATE_LIST_FRIEND_SEND_ITEMS_REQUEST;
            case 111: return PROFILE_DONATE_LIST_FRIEND_SEND_ITEMS_RESPONSE;
            case 112: return PROFILE_ACCUMULATE_PROMOTION_REQUEST;
            case 113: return PROFILE_ACCUMULATE_PROMOTION_RESPONSE;
            case 114: return PROFILE_ACCUMULATE_CLAIM_REQUEST;
            case 115: return PROFILE_ACCUMULATE_CLAIM_RESPONSE;
            case 116: return PROFILE_LEADERBOARD_REQUEST;
            case 117: return PROFILE_LEADERBOARD_RESPONSE;
            case 118: return PROFILE_ARCHIVE_COLLECTION_REQUEST;
            case 119: return PROFILE_ARCHIVE_COLLECTION_RESPONSE;
            case 120: return PROFILE_ADS_INFO_REQUEST;
            case 121: return PROFILE_ADS_INFO_RESPONSE;
            case 122: return PROFILE_ADS_REWARD_CLAIM_REQUEST;
            case 123: return PROFILE_H3_ENTER_REQUEST;
            case 124: return PROFILE_H3_ENTER_RESPONSE;
            case 125: return PROFILE_H3_LEAVE_REQUEST;
            case 126: return PROFILE_H3_LEAVE_RESPONSE;
            case 127: return PROFILE_H3_TURN_REQUEST;
            case 128: return PROFILE_H3_TURN_RESPONSE;
            default: return UNRECOGNIZED;
        }
    }
}